name: Java CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  repository_dispatch:
    branches: [main]
    types: image_updated

jobs:
  java-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        distribution: ["adopt"]
        java-version: [11]

    steps:
      - uses: actions/checkout@v2
      - name: check code format
        uses: axel-op/googlejavaformat-action@v3
        with:
          version: "1.10.0"
          skipCommit: true
          args: "--set-exit-if-changed"

      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: logs-artifact
          path: |
            .logs
            app/build/reports

      - name: Post to Slack channel
        if: ${{ github.event.client_payload.notify }} && ${{ failure() }}
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "${{ env.SLACK_MESSAGE_TEXT }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ env.SLACK_MESSAGE_TEXT }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_MESSAGE_TEXT: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
