name: Java CI on Repository Dispatch
on:
  repository_dispatch:
    branches: [main]
    types: image_updated

jobs:
  java-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        distribution: ["adopt"]
        java-version: [11]

    steps:
      - uses: actions/checkout@v2
      - name: check code format
        uses: axel-op/googlejavaformat-action@v3
        with:
          version: "1.10.0"
          skipCommit: true
          args: "--set-exit-if-changed"

      - uses: actions/setup-java@v2
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java-version }}
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        if: ${{ success() }} || ${{ failure() }}
        with:
          name: logs-artifact
          path: |
            .logs
            app/build/reports

      - name: Post to Slack channel
        if: ${{ success() }} || ${{ failure() }}
        run: |
          curl                                  \
            -X POST                             \
            -H 'Content-Type: application/json' \
            ${{ secrets.SLACK_WEB_HOOK_URL }}   \
            --data "{\"data\": \"GitHub Action build result: ${{ job.status }}\n\
              Commit info: https://github.com/hstreamdb/hstream/commit/${{ github.event.client_payload.commit_sha }}\n\
              Action summary: https://github.com/hstreamdb/integration-tests/actions/runs/${{ env.GITHUB_RUN_ID }}\"}"
